### ISSUE TITLE
when i try to go on a savefile this happens (i know someone has reported this error but it happens to me too)

### ISSUE THREAD

**Issue by EstanisIsCool** [AurieFramework/YYToolkit#18]
![image](https://user-images.githubusercontent.com/91768774/135701652-481562e4-66c6-457e-99c3-80cd6cda9a90.png)

**Comment by TheBusinessPyro** [comment]
copy the error and send it here so its easier for him to read it

**Comment by Archie-osu** [comment]
Found the issue - it seems that the bytecode I used to disable it is now invalid - working on a fix.

**Comment by Archie-osu** [comment]
Fixed in #19, closing.
