### ISSUE TITLE
deltarune is only showing like a 4th of the screen

### ISSUE THREAD

**Issue by Bloo-Snoc** [AurieFramework/YYToolkit#22]
with mods:
![image](https://user-images.githubusercontent.com/92127849/136475668-794a9831-bbb1-44c3-93e1-3afd99a61dcb.png)
without mods:
![image](https://user-images.githubusercontent.com/92127849/136475719-bf09f576-e1ec-46ed-bde0-37e52b8fb829.png)

**Comment by Archie-osu** [comment]
Hi, I couldn't reproduce this issue, and will thus need more info.

Please answer the following:
- What's the resolution of all screens (monitors) you have connected?
- Does the issue happen when YYToolkit is launched with no plugins?
- Does the issue persist after going into / out of fullscreen mode?

**Comment by Archie-osu** [comment]
Progress is now being tracked in #23, closing.
