### ISSUE TITLE
full screen issue

### ISSUE THREAD

**Issue by PixelAsh** [AurieFramework/YYToolkit#23]
Everytime i go into fullscreen with mods on then it gets weird and stretches everything. I tried with no mods and it works perfectly fine, can you help me or fix the code? 
![DELTARUNE Chapter 2 10_8_2021 4_35_08 PM](https://user-images.githubusercontent.com/92184930/136622360-f5f55338-7519-41a0-a970-9571b2814e80.png)

**Comment by Archie-osu** [comment]
Thank you for reporting the issue, I managed to successfully reproduce it, and an investigation is ongoing. I'll close this issue when I fix it.

**Comment by Archie-osu** [comment]
The cause of this issue has been pinpointed, a fix is being worked on.

**Comment by Archie-osu** [comment]
Most likely fixed in #24, feel free to reopen if the issue persists.

**Comment by Bloo-Snoc** [comment]
its fixed
