### ISSUE TITLE
Just pressing cancel on the room teleporter automatically Dogchecks.

### ISSUE THREAD

**Issue by custardcheesitsreal** [AurieFramework/YYToolkit#30]
![image](https://user-images.githubusercontent.com/97194377/148282788-43ddf409-a13d-4d21-8344-3bac8e06efb3.png)
![image](https://user-images.githubusercontent.com/97194377/148282844-4424e683-6884-4d99-b808-9932f2581882.png)

**Comment by Archie-osu** [comment]
This won't be fixed, as it's correct behavior (see documentation of get_integer in GameMaker).
