### ISSUE TITLE
YYToolkit unloading in game

### ISSUE THREAD

**Issue by lol90101** [AurieFramework/YYToolkit#47]
While playing Deltarune, sometimes YYToolkit unloads for no reason, disabling all debug features. How do I disable this as it is annoying

**Comment by Archie-osu** [comment]
Are you perhaps pressing the END key on accident? YYTK shouldn't unload itself unless that key is pressed.

**Comment by lol90101** [comment]
Turns out that was the problem. thanks

**Comment by lol90101** [comment]
It seemed to mostly happen when I was pressing INSERT to teleport through rooms as it was easy to slip on END and unload YYTK by mistake
