### ISSUE TITLE
Can't execute a script using script_execute()

### ISSUE THREAD

**Issue by EdyDude** [AurieFramework/YYToolkit#51]
![image](https://github.com/Archie-osu/YYToolkit/assets/80089930/9c6fb149-13ab-419b-bf71-19bfbfdb361f)

**Comment by Archie-osu** [comment]
What game and what script are you trying to execute?

**Comment by EdyDude** [comment]
Godzilla Creepypasta 0.0.2. The scripts that i want to execute is: script_execute(84) for draining health, script_execute(85) for draining power, script_execute(86) for recovering health and script_execute(87) for recovering power.

**Comment by Archie-osu** [comment]
Upon further research, this seems to be due to missing arguments. Closing.

**Comment by fixdude** [comment]
you need to input additional arguments. i don't know what they do. so just put in 2 or 3 zeros

**Comment by EdyDude** [comment]
I'll try
