### ISSUE TITLE
YYToolkit fails on Crashlands 2 - Demo

### ISSUE THREAD

**Issue by Archie-osu** [AurieFramework/YYToolkit#68]
Runner interface isn't found.

**Comment by Archie-osu** [comment]
Not actually fixed, runner interface is now wrongly offset.

**Comment by Archie-osu** [comment]
Similar issue is present on Conscript Demo.

**Comment by retcinder** [comment]
Note: Crashlands 2's demo is no longer available nor functional. Testing would need to be done on a game with a similar issue.

**Comment by Rukongai** [comment]
Similar issue happening with Fields of Mistria - no demo available however.

-------

I'm willing to gift a copy of the game if it'll assist in support it.

**Comment by DeathMunchkin** [comment]
Seconding Rukongai, Fields of Mistria is throwing a runner interface error
![Screenshot 2024-09-15 141153](https://github.com/user-attachments/assets/1fcbd9fd-c338-44f8-ba2a-8ea9f307e5c3)
