### ISSUE TITLE
YYtoolkit crashes when i try to load deltarune

### ISSUE THREAD

**Issue by TheBusinessPyro** [AurieFramework/YYToolkit#9]
deltarune sometimes loads up but only as a background process and the toolkit crashes whenever i try to load dr

**Comment by Archie-osu** [comment]
What chapter of DR are you trying to load? Are there any plugins present? If so, try disabling them through the Launcher.

**Comment by TheBusinessPyro** [comment]
chp2

**Comment by TheBusinessPyro** [comment]
using the itch io version doesnt have any bugs doe

**Comment by Archie-osu** [comment]
Oh so it only happens with the Steam version?
If so, how exactly does DELTARUNE crash? Do you get a code error window, or is it just a generic "DELTARUNE.exe has stopped working" message?

**Comment by TheBusinessPyro** [comment]
Deltarune doesnt crash, its toolkit. When I try using the steam version of deltarune, toolkit crashes and makes deltarune a bg process

**Comment by Archie-osu** [comment]
Ah, then I already got the fix implemented!

It should be resolved when 0.0.6 gets merged into stable, which may be either today or tomorrow.

**Comment by Archie-osu** [comment]
@sm64onlydude If you can, check again with version 0.0.6 and report if it got fixed.

**Comment by TheBusinessPyro** [comment]
should i download the yytoolkit dll or just the launcher since i already have the example dll

**Comment by TheBusinessPyro** [comment]
still crashes so maybe its my version of deltarune

**Comment by TheBusinessPyro** [comment]
also deltarune seems to load in a little bit later now

**Comment by Archie-osu** [comment]
> should i download the yytoolkit dll or just the launcher since i already have the example dll

You should download the launcher and the ExamplePlugin, both were updated.

**Comment by Archie-osu** [comment]
Also, are you able to record the process of loading so I can get a better idea of what happens?

**Comment by TheBusinessPyro** [comment]
first one ok second one will try

**Comment by Araraura** [comment]
Are you using the PDUI plugin? It was crashing for me as well but after removing it, it worked again.

**Comment by TheBusinessPyro** [comment]
whats that?

**Comment by Archie-osu** [comment]
That's a plugin for cross-room teleportation - it was never shared on this repo and only recently have the sources been released in the plugin repo.

**Comment by TheBusinessPyro** [comment]
also steam deleted all my games so might take a while to do tests again

**Comment by Archie-osu** [comment]
No feedback for 7 days, closing. Feel free to reopen if the issue persists.
